version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      timezone: "Europe/Berlin"
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - nikcani
